import { Task, ScheduleItem } from "../types";

export const formatDate = (dateString: string): string => {
  try {
    const date = new Date(dateString);
    if (isNaN(date.getTime())) return "Invalid Date";
    return new Intl.DateTimeFormat('en-US', {
      month: 'short',
      day: 'numeric',
      hour: 'numeric',
      minute: 'numeric',
    }).format(date);
  } catch (e) {
    return dateString;
  }
};

// Converts UTC ISO string to "YYYY-MM-DDThh:mm" for <input type="datetime-local">
// This prevents time shifting due to timezone offsets when editing.
export const toLocalInputString = (isoString: string): string => {
  if (!isoString) return '';
  try {
    const date = new Date(isoString);
    if (isNaN(date.getTime())) return '';
    
    // Build local string manually to preserve wall-clock time
    const pad = (n: number) => n.toString().padStart(2, '0');
    const year = date.getFullYear();
    const month = pad(date.getMonth() + 1);
    const day = pad(date.getDate());
    const hours = pad(date.getHours());
    const minutes = pad(date.getMinutes());
    
    return `${year}-${month}-${day}T${hours}:${minutes}`;
  } catch (e) {
    return '';
  }
};

export const getGoogleCalendarUrl = (task: Task): string => {
  try {
    const startDate = new Date(task.dueDate);
    if (isNaN(startDate.getTime())) return '#';
    
    // Default duration of 1 hour
    const endDate = new Date(startDate.getTime() + 60 * 60 * 1000);

    const formatGoogleDate = (date: Date) => {
      return date.toISOString().replace(/-|:|\.\d\d\d/g, "");
    };

    const startStr = formatGoogleDate(startDate);
    const endStr = formatGoogleDate(endDate);

    const url = new URL('https://calendar.google.com/calendar/render');
    url.searchParams.append('action', 'TEMPLATE');
    url.searchParams.append('text', task.title);
    url.searchParams.append('details', task.description + "\n\nGenerated by TaskFlow AI");
    url.searchParams.append('dates', `${startStr}/${endStr}`);

    return url.toString();
  } catch (e) {
    console.error("Calendar URL Error", e);
    return '#';
  }
};

export const getScheduleCalendarUrl = (item: ScheduleItem, dateStr: string): string => {
  // Helper to parse "09:00 - 10:00" or similar formats
  const parseTime = (timeStr: string, baseDateStr: string): Date => {
    const d = new Date(baseDateStr);
    
    // Normalize time string (remove whitespace, lowercase)
    const cleanTime = timeStr.trim().toLowerCase();
    
    // Handle "9am" or "9:00am" formats roughly if they appear
    const isPM = cleanTime.includes('pm');
    const isAM = cleanTime.includes('am');
    const timeOnly = cleanTime.replace(/(am|pm)/g, '').trim();
    
    const [hoursStr, minutesStr] = timeOnly.split(':');
    let hours = parseInt(hoursStr, 10);
    const minutes = parseInt(minutesStr || '0', 10);
    
    if (isNaN(hours)) throw new Error("Invalid time format");

    if (isPM && hours < 12) hours += 12;
    if (isAM && hours === 12) hours = 0;
    
    d.setHours(hours);
    d.setMinutes(minutes);
    d.setSeconds(0);
    return d;
  };

  try {
    // Expected format "09:00 - 10:00" or "09:00 to 10:00"
    const parts = item.time.split(/-|to/); 
    
    let startDate = parseTime(parts[0], dateStr);
    let endDate;
    
    if (parts.length > 1 && parts[1].trim()) {
        try {
            endDate = parseTime(parts[1], dateStr);
        } catch {
             endDate = new Date(startDate.getTime() + 60 * 60 * 1000);
        }
    } else {
        endDate = new Date(startDate.getTime() + 60 * 60 * 1000); // Default 1 hour
    }

    // Format for Google Calendar URL (YYYYMMDDTHHMMSSZ)
    const formatGoogleDate = (date: Date) => {
      return date.toISOString().replace(/-|:|\.\d\d\d/g, "");
    };

    const startStr = formatGoogleDate(startDate);
    const endStr = formatGoogleDate(endDate);

    const url = new URL('https://calendar.google.com/calendar/render');
    url.searchParams.append('action', 'TEMPLATE');
    url.searchParams.append('text', item.activity);
    url.searchParams.append('details', (item.notes || "") + "\n\nGenerated by TaskFlow AI Planner");
    url.searchParams.append('dates', `${startStr}/${endStr}`);

    return url.toString();
  } catch (e) {
    console.warn("Failed to generate calendar URL for schedule item:", item.time);
    return "#";
  }
};

export const getMailtoLink = (email: string, subject: string, body: string): string => {
  const encodedSubject = encodeURIComponent(subject);
  // Truncate body to avoid URL length limits if necessary
  const safeBody = body.length > 1500 ? body.substring(0, 1500) + "..." : body;
  const encodedBody = encodeURIComponent(safeBody);
  return `mailto:${email}?subject=${encodedSubject}&body=${encodedBody}`;
};