import { Task, ScheduleItem } from "../types";

export const formatDate = (dateString: string): string => {
  const date = new Date(dateString);
  return new Intl.DateTimeFormat('en-US', {
    month: 'short',
    day: 'numeric',
    hour: 'numeric',
    minute: 'numeric',
  }).format(date);
};

export const getGoogleCalendarUrl = (task: Task): string => {
  const startDate = new Date(task.dueDate);
  // Default duration of 1 hour
  const endDate = new Date(startDate.getTime() + 60 * 60 * 1000);

  const formatGoogleDate = (date: Date) => {
    return date.toISOString().replace(/-|:|\.\d\d\d/g, "");
  };

  const startStr = formatGoogleDate(startDate);
  const endStr = formatGoogleDate(endDate);

  const url = new URL('https://calendar.google.com/calendar/render');
  url.searchParams.append('action', 'TEMPLATE');
  url.searchParams.append('text', task.title);
  url.searchParams.append('details', task.description + "\n\nGenerated by TaskFlow AI");
  url.searchParams.append('dates', `${startStr}/${endStr}`);

  return url.toString();
};

export const getScheduleCalendarUrl = (item: ScheduleItem, dateStr: string): string => {
  // Helper to parse "09:00 - 10:00" or similar formats
  const parseTime = (timeStr: string, baseDateStr: string): Date => {
    const d = new Date(baseDateStr);
    const [hoursStr, minutesStr] = timeStr.trim().replace(/(am|pm)/i, '').split(':');
    let hours = parseInt(hoursStr, 10);
    const minutes = parseInt(minutesStr || '0', 10);
    
    // Simple 12h to 24h conversion if AM/PM detected
    if (timeStr.toLowerCase().includes('pm') && hours < 12) hours += 12;
    if (timeStr.toLowerCase().includes('am') && hours === 12) hours = 0;
    
    if (!isNaN(hours)) d.setHours(hours);
    if (!isNaN(minutes)) d.setMinutes(minutes);
    d.setSeconds(0);
    return d;
  };

  try {
    const parts = item.time.split(/-|to/); // Handle "09:00 - 10:00" or "09:00 to 10:00"
    
    let startDate = parseTime(parts[0], dateStr);
    let endDate = parts.length > 1 ? parseTime(parts[1], dateStr) : new Date(startDate.getTime() + 60 * 60 * 1000); // Default 1 hour if no end time

    // Format for Google Calendar URL (YYYYMMDDTHHMMSSZ)
    const formatGoogleDate = (date: Date) => {
      return date.toISOString().replace(/-|:|\.\d\d\d/g, "");
    };

    const startStr = formatGoogleDate(startDate);
    const endStr = formatGoogleDate(endDate);

    const url = new URL('https://calendar.google.com/calendar/render');
    url.searchParams.append('action', 'TEMPLATE');
    url.searchParams.append('text', item.activity);
    url.searchParams.append('details', (item.notes || "") + "\n\nGenerated by TaskFlow AI Planner");
    url.searchParams.append('dates', `${startStr}/${endStr}`);

    return url.toString();
  } catch (e) {
    console.error("Failed to generate calendar URL for schedule item", e);
    return "#";
  }
};

export const getMailtoLink = (email: string, subject: string, body: string): string => {
  const encodedSubject = encodeURIComponent(subject);
  const encodedBody = encodeURIComponent(body);
  return `mailto:${email}?subject=${encodedSubject}&body=${encodedBody}`;
};